apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "storage"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "managed-premium-retain"
  resources:
    requests:
      storage: 5Gi
