apiVersion: v1
data:
  test-auth: {{ .Files.Get "basic_auth.txt" | b64enc }}
kind: Secret
metadata:
  name: basic-auth
type: kubernetes.io/basic-auth

--- 
apiVersion: v1
data:
  cert.pem: {{ .Files.Get "cert.pem" | b64enc }}
  cert-key.key: {{ .Files.Get "cert-key.key" | b64enc }}
kind: Secret
metadata:
  name: nginx-ssl
type: "Opaque"