apiVersion: v1
kind: Service
metadata:
  name: "nginx-cardinality"
  labels:
    app: {{ include "service.fullname" . }}
    app.kubernetes.io/name: {{ include "service.name" . }}
    helm.sh/chart: {{ include "service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: http
  selector:
    app: "nginx-cardinality"
---
apiVersion: v1
kind: Service
metadata:
  name: "nginx-cardinality-nodePort"
  labels:
    app: {{ include "service.fullname" . }}
    app.kubernetes.io/name: {{ include "service.name" . }}
    helm.sh/chart: {{ include "service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: http
      nodePort: 30080
  selector:
    app: "nginx-cardinality"